[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
gobject-sys = "0.6.0"
glib-sys = "0.6.0"
gdk-sys = "0.6.0"
cairo-sys-rs = "0.6.0"
gio-sys = "0.6.0"
atk-sys = "0.6.0"
pango-sys = "0.6.0"
gdk-pixbuf-sys = "0.6.0"
libc = "0.2"
bitflags = "1.0"

[features]
dox = []
v3_6 = []
v3_8 = ["v3_6"]
v3_10 = ["v3_8"]
v3_12 = ["v3_10"]
v3_14 = ["v3_12"]
v3_16 = ["v3_14"]
v3_18 = ["v3_16"]
v3_20 = ["v3_18"]
v3_22 = ["v3_20"]
v3_22_26 = ["v3_22_6"]
v3_22_6 = ["v3_22"]

[lib]
name = "gtk_sys"

[package]
name = "gtk-sys"
license = "MIT"
homepage = "http://gtk-rs.org/"
links = "gtk"
authors = ["The Gtk-rs Project Developers"]
description = "FFI bindings to libgtk-3"
version = "0.6.0"
keywords = ["gtk", "ffi", "gtk-rs", "gnome"]
repository = "https://github.com/gtk-rs/sys"
build = "build.rs"
