
[build-dependencies]
pkg-config = "0.3.5"

[dependencies]
bitflags = "0.3"
libc = "0.1"

[dependencies.gio-sys]
path = "../gio-sys"
version = "^0.2.0"

[dependencies.glib-sys]
path = "../glib-sys"
version = "^0.2.0"

[dependencies.gobject-sys]
path = "../gobject-sys"
version = "^0.2.0"

[lib]
name = "gdk_pixbuf_sys"

[package]
build = "build.rs"
links = "gdk_pixbuf"
name = "gdk-pixbuf-sys"
version = "0.2.2"
