dist: xenial
language: rust
rust:
  - nightly
  - beta
  - 1.34.0 # stable
env:
  - GTK=3.14
  - GTK=3.24
  - GTK=3.96
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] && [ "$GTK" == "3.14" ]; then
    rustup component add rustfmt;
    make regen_check;
    fi
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - if [ "$GTK" == "3.96" ]; then
    git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples4 _examples;
    else
    git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples;
    fi
  - cd _examples
  - ./build_travis.sh
