
[build-dependencies]
pkg-config = "0.3.5"

[dependencies]
bitflags = "0.3"
libc = "0.1"

[dependencies.glib-sys]
path = "../glib-sys"
version = "^0.2.2"

[lib]
name = "gobject_sys"

[package]
build = "build.rs"
links = "gobject"
name = "gobject-sys"
version = "0.2.1"
