
[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.4"
libc = "0.2"

[dependencies.glib-sys]
path = "../glib-sys"
version = "0.3.0"

[features]
"2.34" = []
"2.36" = ["2.34"]
"2.38" = ["2.36"]
"2.42" = ["2.38"]
"2.44" = ["2.42"]

[lib]
name = "gobject_sys"

[package]
build = "build.rs"
links = "gobject"
name = "gobject-sys"
version = "0.3.0"
