
[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.4"
libc = "0.2"

[features]
"2.34" = []
"2.36" = ["2.34"]
"2.38" = ["2.36"]
"2.40" = ["2.38"]
"2.44" = ["2.40"]

[lib]
name = "glib_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libglib-2.0"
homepage = "http://gtk-rs.org/"
keywords = ["glib", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "glib"
name = "glib-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.3.0"
