
[build-dependencies]
pkg-config = "0.3.5"

[dependencies]
bitflags = "0.4"
libc = "0.2"

[dependencies.glib-sys]
path = "../glib-sys"
version = "0.3.0"

[dependencies.gobject-sys]
path = "../gobject-sys"
version = "0.3.0"

[features]
"2.10" = ["2.9.4"]
"2.12" = ["2.10"]
"2.7.90" = []
"2.8" = ["2.7.90"]
"2.9.3" = ["2.8"]
"2.9.4" = ["2.9.3"]

[lib]
name = "atk_sys"

[package]
build = "build.rs"
links = "atk"
name = "atk-sys"
version = "0.3.0"
