[options]
work_mode = "sys"
library = "GdkPixbuf"
version = "2.0"
min_cfg_version = "2.26"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]

[[object]]
name = "GdkPixbuf.Pixbuf"
status = "generate"
    [[object.function]]
    pattern = "new_from_file.*"
    is_windows_utf8 = true
    [[object.function]]
    pattern = "savev?"
    is_windows_utf8 = true
    [[object.function]]
    name = "new_from_file"
    is_windows_utf8 = true

[[object]]
name = "GdkPixbuf.PixbufAnimation"
status = "generate"
    [[object.function]]
    name = "new_from_file"
    is_windows_utf8 = true
