[options]
work_mode = "normal"
girs_dir = "gir-files"
library = "Gdk"
version = "3.0"
min_cfg_version = "3.4"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "GdkPixbuf",
   "Pango",
   "Cairo",
]
