[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "1.0"
libc = "0.2"
cairo-sys-rs = "0.4.0"
glib-sys = "0.4.0"
pango-sys = "0.4.0"

[features]
dox = []

[lib]
name = "pango_cairo_sys"

[package]
build = "build.rs"
links = "pango_cairo"
name = "pangocairo-sys"
version = "0.4.1"
